### Create user
POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "12345678"
  }


### Sign in as an existing user
POST  http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "12345678"
  }

### ge current user
GET  http://localhost:3000/auth/whoami

### Sign out
POST  http://localhost:3000/auth/signout

### Login

POST  http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "snabin@gmail45.com",
    "password": "123456786"
  }

### find user

GET http://localhost:3000/auth/4


### Find all users with a given email

GET http://localhost:3000/auth?email=abc@gmail.com


### Delete user

DELETE  http://localhost:3000/auth/2

### Update user

PATCH  http://localhost:3000/auth/3
Content-Type: application/json

{
    "email": "hello@gmail.com"
}

# ### Set a color

# GET http://localhost:3000/auth/colors/blue

# ### Set a color

# GET http://localhost:3000/auth/colors